package Vista;

import Clases.Vertice;
import Clases.Arista;
import Logica.VerticesLogica;
import Logica.AristasLogica;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author jm543
 */
public class Panel extends javax.swing.JPanel {

    public Panel() {
        initComponents();
        setBackground(Color.CYAN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        try {
            for (Arista Lineas : AristasLogica.getAristas()) {
                Lineas.draw(g);
                g.setColor(Color.BLACK);
                Font font = new Font("Arial", Font.BOLD, 10);
                g.setFont(font);
                g.drawString(Lineas.getTexto(), ((Lineas.getX2()-Lineas.getX1())/2)+Lineas.getX1(), ((Lineas.getY2()-Lineas.getY1())/2)+Lineas.getY1() );
            }
            for (Vertice circulo : VerticesLogica.getVertice()) {
                circulo.draw(g);
                g.setColor(Color.BLACK);
                Font font = new Font("Arial", Font.BOLD, 20);
                g.setFont(font);
                g.drawString(circulo.getIdentificador()+"", circulo.getX()-5, circulo.getY()+5);
            }
        } catch (Exception e) {
            repaint();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
